version: '3'

services:
    db:
       image: postgres
       environment:
            POSTGRES_PASSWORD: postgres
       volumes:
          - F:\Shruti\Challenges\CELUS\postgres_data:/var/lib/postgresql/data
       ports:
          - "5432:5432"
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: chikode44@gmail.com
            PGADMIN_DEFAULT_PASSWORD: test123
        ports:
          - "8080:80"
        depends_on:
          - db