version: '3'

services:
    db:
       image: postgres
       environment:
            POSTGRES_PASSWORD: postgres
       volumes:
          - .:/var/lib/docker/volume
       ports:
          - "5432:5432"
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: root@root1.com
            PGADMIN_DEFAULT_PASSWORD: test123
        ports:
          - "8080:80"
        depends_on:
          - db