version: '3'

services:
    db:
       image: ${POSTGRES_IMAGE}
       environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
       volumes:
          - .:/var/lib/docker/volume
       ports:
          - "5432:5432"
    pgadmin:
        image: ${PGADMIN_IMAGE}
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        ports:
          - "127.0.0.1:5000:5000"
        depends_on:
          - db